name: 'Build'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: 'Build'
        env:
          GOOS: 'linux'
          GOARCH: 'arm64'
          CGO_ENABLED: '0'
        run: 'go build -o bootstrap -tags "lambda,lambda.norpc"'
      - name: 'Prepare lambda bundle'
        run: '(chmod +x bootstrap && zip -q lambda_bundle.zip bootstrap && rm bootstrap)'
      - name: 'Store artifact'
        uses: actions/upload-artifact@v4
        with:
          name: 'lambda_bundle.zip'
          path: 'lambda_bundle.zip'